OCR_REPLACEMENTS = {
    "circula;on": "circulation",
    "circula;ons": "circulations",
    "circula8on": "circulation",
    "protec;on": "protection",
    "protec8on": "protection",
    "posi;on": "position",
    "installa;on": "installation",
    "installa;ons": "installations",
    "installa8ons": "installations",
    "condi;ons": "conditions",
    "ar;cle": "article",
    "ar8cle": "article",
    "par;e": "partie",
    "trac;on": "traction",
    "trac8on": "traction",
    "récep;on": "réception",
    "récep8on": "réception",
    "communica8on": "communication",
    "condi8ons": "conditions",
}